version: '2.1'

services:
  web:
      build:
        context: ./Pranav/auth-service
        dockerfile: Dockerfile
      command: python __init__.py
      ports:
        - 3000:3000
      depends_on:
        db:
          condition: service_started
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flaskJWT
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 2s
      retries: 5
